name: "Test DDEV Addon"
on:
  pull_request:
  merge_group:

jobs:
  run_tests:
    name: Run tests
    uses: oblakstudio/ddev-minio/.github/workflows/reusable_test_ddev_addon.yml@master
    with:
      test_type: "local"
